-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 16:38:39 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epicollect5
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `epicollect5`;
CREATE SCHEMA IF NOT EXISTS `epicollect5` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

-- CREATE USER 'epi_admin'@'localhost' IDENTIFIED BY 'epi_adminpw';
-- GRANT USAGE ON *.* TO 'epi_admin'@'localhost'
-- REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
-- GRANT ALL PRIVILEGES ON `epicollect5`.* TO 'epi_admin'@'localhost' WITH GRANT OPTION;


USE `epicollect5` ;

-- -----------------------------------------------------
-- Table `epicollect5`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epicollect5`.`users` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(100) NOT NULL,
 `email` varchar(255) NOT NULL,
 `password` varchar(255) NOT NULL,
 `avatar` varchar(200) NOT NULL,
 `provider` varchar(200) NOT NULL,
 `remember_token` varchar(200) NOT NULL,
 `server_role` enum('basic','admin','superadmin') NOT NULL DEFAULT 'basic',
 `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `state` enum('active','disabled') NOT NULL DEFAULT 'active',
 `api_token` varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY (`id`),
 UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4031 DEFAULT CHARSET=utf8;

